// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnweIiwfFtJhv8APldjVxC4zKp-1qFoBw',
    appId: '1:146429905842:web:efadcddb9e0bbaa21ab2ab',
    messagingSenderId: '146429905842',
    projectId: 'orderingmobile',
    authDomain: 'orderingmobile.firebaseapp.com',
    storageBucket: 'orderingmobile.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQKuzmv6xMhAcYU3iMk7ykTUrt8kSZUB8',
    appId: '1:146429905842:android:b2164d2118fd6c431ab2ab',
    messagingSenderId: '146429905842',
    projectId: 'orderingmobile',
    storageBucket: 'orderingmobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgzVwXd2pzdYPgJaj5an3INzJ-dlJCX0w',
    appId: '1:146429905842:ios:4b0373fc40cda1dd1ab2ab',
    messagingSenderId: '146429905842',
    projectId: 'orderingmobile',
    storageBucket: 'orderingmobile.firebasestorage.app',
    iosBundleId: 'com.example.assignment1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgzVwXd2pzdYPgJaj5an3INzJ-dlJCX0w',
    appId: '1:146429905842:ios:4b0373fc40cda1dd1ab2ab',
    messagingSenderId: '146429905842',
    projectId: 'orderingmobile',
    storageBucket: 'orderingmobile.firebasestorage.app',
    iosBundleId: 'com.example.assignment1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnweIiwfFtJhv8APldjVxC4zKp-1qFoBw',
    appId: '1:146429905842:web:beaee67e7d25473b1ab2ab',
    messagingSenderId: '146429905842',
    projectId: 'orderingmobile',
    authDomain: 'orderingmobile.firebaseapp.com',
    storageBucket: 'orderingmobile.firebasestorage.app',
  );
}
